using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using System.Linq;
using System;
using Random = UnityEngine.Random;

public class WordPasscode : Puzzle
{

    // Sets the parent fields
    /*
    void Awake()
    {
        puzzleName = "WordPasscode";
        difficulty = NextSceneManager.instance.setPuzzledifficulty;
        placeholder = NextSceneManager.instance.placeholder;
        Debug.Log("Difficulty for puzzle " + puzzleName + " is: " + this.difficulty);
    }
    */

    /* Your wonderful startup puzzle code here :3 */
    // This code automatically generated by TableCodeGen

    //list of questions
    public Questions[] questions;

    //list of unanswered questions
    private static List<Questions> unansweredQuestions;

    private Questions currentQuestion;

    //variable to store random integer for question randomization
    private int randQuestionIndex;

    //counter variables
    //try making these static so they dont reset after scene is restarted
    //take the variables out from Question.cs
    private int totalQuestionsAnswered;
    private int numErrors;

    [SerializeField]
    private Text questionText;

    [SerializeField]
    private Text optionA;

    [SerializeField]
    private Text optionB;

    [SerializeField]
    private Text optionC;

    [SerializeField]
    private Text optionD;

    [SerializeField]
    private Text incorrectAnswers;

    //sound files for correct/incorrect answer
    public AudioSource correct;
    public AudioSource incorrect;

    //difficulty buttons
    //need to get code to hide buttons after difficulty selected
    Button easy;
    Button medium;
    Button hard;

    private void Start()
    {
        //reset error counter
        totalQuestionsAnswered = 1;
        numErrors = 0;

        //load all unanswered questions into unanswered question list
        if (unansweredQuestions == null || unansweredQuestions.Count == 0)
        {
            unansweredQuestions = questions.ToList<Questions>();
        }

        //get a random question -- comment out for difficulties?
        //SetCurrentQuestion();
        
    }

    /*
    void HideButton()
    {
        medium.gameObject.SetActive(false);
        hard.gameObject.SetActive(false);
    }
    */
    public void Easy_Difficulty()
    {
        randQuestionIndex = Random.Range(0, 20);
        SetCurrentQuestion();
        //medium = GetComponent<Button>();
        //medium.onClick.AddListener(() => HideButton());
        //hard = GetComponent<Button>();
        //hard.onClick.AddListener(() => HideButton());

    }

    public void Medium_Difficulty()
    {
        randQuestionIndex = Random.Range(21, 39);
        SetCurrentQuestion();
    }

    public void Hard_Difficulty()
    {
        randQuestionIndex = Random.Range(40, 59);
        SetCurrentQuestion();
    }
    
    void SetCurrentQuestion()
    {

        //proper code. 
        //int randQuestionIndex = Random.Range(0, unansweredQuestions.Count);

        //set current question to randomly selected question
        currentQuestion = unansweredQuestions[randQuestionIndex];

        //display question in panel
        questionText.text = currentQuestion.question;

        //display multiple choice options
        optionA.text = currentQuestion.a;
        optionB.text = currentQuestion.b;
        optionC.text = currentQuestion.c;
        optionD.text = currentQuestion.d;

        incorrectAnswers.text = numErrors.ToString();

        
    }

    //transition to next question
    void LoadNextQuestion()
    {
        //10 questions to complete a difficulty
        if (totalQuestionsAnswered < 11)
        {
            //remove element -- not index
            unansweredQuestions.Remove(currentQuestion);
            SetCurrentQuestion();
        }
        else
        {
            questionText.text = "Finished!";
            optionA.text = "";
            optionB.text = "";
            optionC.text = "";
            optionD.text = "";
        }
       
    }

    //code for users selected answer
    //option A
    public void UserSelectA()
    {
        if (currentQuestion.a == currentQuestion.answer)
        {
            Debug.Log("CORRECT");
            //correct.Play();
            Invoke("LoadNextQuestion", 0.5f);
            Debug.Log("total questions wrong " + numErrors);
            Debug.Log("TOTAL ANSWERED: " + totalQuestionsAnswered);
            totalQuestionsAnswered += 1;
        } else
        {
            Debug.Log("INCORRECT");
            //incorrect.Play();
            numErrors += 1;
            Debug.Log("total questions wrong " + numErrors);
        }
    }

    //option B
    public void UserSelectB() {

        if (currentQuestion.b == currentQuestion.answer)
        {
            Debug.Log("CORRECT");
            //correct.Play(); 
            Invoke("LoadNextQuestion", 0.5f);
            Debug.Log("total questions wrong " + numErrors);
            Debug.Log("TOTAL ANSWERED: " + totalQuestionsAnswered);
            totalQuestionsAnswered += 1;
        }
        else
        {
            Debug.Log("INCORRECT");
            //incorrect.Play();
            numErrors += 1;
            Debug.Log("total questions wrong " + numErrors);

        }
    }

    //option C
    public void UserSelectC() {

        if (currentQuestion.c == currentQuestion.answer)
        {
            Debug.Log("CORRECT");
            //correct.Play();         
            Invoke("LoadNextQuestion", 0.5f);
            Debug.Log("total questions wrong " + numErrors);
            Debug.Log("TOTAL ANSWERED: " + totalQuestionsAnswered);
            totalQuestionsAnswered += 1;
        }
        else
        {
            Debug.Log("INCORRECT");
            //incorrect.Play();
            numErrors += 1;
            Debug.Log("total questions wrong " + numErrors);

        }
           
    }

    //option D
    public void UserSelectD() {

        if (currentQuestion.d == currentQuestion.answer)
        {
            Debug.Log("CORRECT");
            //correct.Play();
            Invoke("LoadNextQuestion", 0.5f);
            Debug.Log("total questions wrong " + numErrors);
            Debug.Log("TOTAL ANSWERED: " + totalQuestionsAnswered);
            totalQuestionsAnswered += 1;
        }
        else
        {
            Debug.Log("INCORRECT");
            //incorrect.Play();
            numErrors += 1;
            Debug.Log("total questions wrong " + numErrors);     
            }
        }
    }
